### ISSUE TITLE
Error on fresh installation

### ISSUE THREAD

**Issue by dwrolvink** [konishi-project/zimmerman#22]
Hi all, I decided to have a go at installing konishi on my pc (Manjaro).
I installed zimmerman and then higara. They both load, but when I load the front end it gives a red pop up: "Something went wrong during the process". If I then look at the terminal for zimmerman, I see the following error popping up whenever I try to do anything on the front end:

```
127.0.0.1 - - [09/Dec/2018 14:16:30] "OPTIONS /feed HTTP/1.1" 200 -
[2018-12-09 14:16:30,993] ERROR in app: Exception on /feed [GET]
Traceback (most recent call last):
  File "/home/dorus/Programming/zimmerman/konishienv/lib/python3.7/site-packages/jwt/api_jws.py", line 181, in _load
    signing_input, crypto_segment = jwt.rsplit(b'.', 1)
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dorus/Programming/zimmerman/konishienv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dorus/Programming/zimmerman/konishienv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/dorus/Programming/zimmerman/konishienv/lib/python3.7/site-packages/flask_restplus/api.py", line 319, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/dorus/Programming/zimmerman/konishienv/lib/python3.7/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/dorus/Programming/zimmerman/konishienv/lib/python3.7/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/dorus/Programming/zimmerman/konishienv/lib/python3.7/site-packages/flask_jwt_extended/view_decorators.py", line 102, in wrapper
    verify_jwt_in_request()
  File "/home/dorus/Programming/zimmerman/konishienv/lib/python3.7/site-packages/flask_jwt_extended/view_decorators.py", line 31, in verify_jwt_in_request
    jwt_data = _decode_jwt_from_request(request_type='access')
  File "/home/dorus/Programming/zimmerman/konishienv/lib/python3.7/site-packages/flask_jwt_extended/view_decorators.py", line 265, in _decode_jwt_from_request
    decoded_token = decode_function()
  File "/home/dorus/Programming/zimmerman/konishienv/lib/python3.7/site-packages/flask_jwt_extended/view_decorators.py", line 194, in _decode_jwt_from_headers
    return decode_token(encoded_token)
  File "/home/dorus/Programming/zimmerman/konishienv/lib/python3.7/site-packages/flask_jwt_extended/utils.py", line 80, in decode_token
    csrf_value=csrf_value
  File "/home/dorus/Programming/zimmerman/konishienv/lib/python3.7/site-packages/flask_jwt_extended/tokens.py", line 129, in decode_jwt
    data = jwt.decode(encoded_token, secret, algorithms=[algorithm])
  File "/home/dorus/Programming/zimmerman/konishienv/lib/python3.7/site-packages/jwt/api_jwt.py", line 85, in decode
    payload, _, _, _ = self._load(jwt)
  File "/home/dorus/Programming/zimmerman/konishienv/lib/python3.7/site-packages/jwt/api_jws.py", line 184, in _load
    raise DecodeError('Not enough segments')
jwt.exceptions.DecodeError: Not enough segments
127.0.0.1 - - [09/Dec/2018 14:16:30] "GET /feed HTTP/1.1" 500 -
```

Seems to me like some packages aren't up to date or something. I installed everything using the guide verbatim, and I don't like the idea of manually updating packages in pip (as in the requirements it lists all the needed versions).

Any idea what I'm doing wrong here?

EDIT: So registering didn't work, but I managed to insert myself into the user table and I can log in at least now :)

**Comment by X1Zeth2X** [comment]
This is a known issue, it sends a 500 error code from the frontend if
something went wrong, the 500 error code is caused by not being able to
find the JWT token (Basically not logged in) I'll fix this issue soon.

**Comment by dwrolvink** [comment]
Thanks! Is there a list of known issues somewhere?

**Comment by X1Zeth2X** [comment]
Not yet, still going through finals, I will be doing huge rewrites and
reorganizations for a more well structured and professional application.

**Comment by X1Zeth2X** [comment]
I don't think is an issue itself, just JWT complaining that there isn't any token to the requested API route. See: https://flask-jwt-extended.readthedocs.io/en/latest/basic_usage.html
